### ISSUE TITLE
[Dev] Update the merge_pr script to work with GitHub issues

### ISSUE THREAD

**Issue by raulcd** [apache/arrow-site#285]
The merge_pr script on the arrow-site repo is quite outdated. It still uses JIRA user and password instead of token (https://github.com/apache/arrow-site/blob/master/scripts/merge_pr.py#L31-L32) and it does not work with GitHub issues. We should update it. Probably copying the one from the Arrow repo (https://github.com/apache/arrow/blob/master/dev/merge_arrow_pr.py) and updating some defaults for repo-name, etcetera should be enough.

**Comment by jorisvandenbossche** [comment]
I don't think that causes any problems ;)

I also often have used the merge button here on the arrow-site repo (not all PRs here were always linked to a JIRA issue, so then there is not that much need to use the merge script)

IMO it would be fine to just start using the merge button for all PRs here.

**Comment by kou** [comment]
Can we change the default commit message to "Default to pull request title and description" if we always use the merge button?

See also: https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

**Comment by raulcd** [comment]
> Can we change the default commit message to "Default to pull request title and description" if we always use the merge button?

I can't find anything on the configuration for the `.asf.yaml` about it.

I would propose at this point to remove both the title PR checkers on this repo and the merge script. I am happy to implement a different title checker but if we take a look at the closed PRs we are defacto ignoring the merge script and using the merge button and ignoring the title PR check for this repo.

**Comment by raulcd** [comment]
Also in the exceptional case of an issue being opened on the main Arrow repo that relates to the `arrow-site` I would redirect (clone?) the issue on this repo instead of having to close issues on the main arrow repo on merge, etcetera.

**Comment by kou** [comment]
> I can't find anything on the configuration for the `.asf.yaml` about it.

Could you open an INFRA Jira issue?

**Comment by jorisvandenbossche** [comment]
> Also in the exceptional case of an issue being opened on the main Arrow repo that relates to the `arrow-site` I would redirect (clone?) the issue on this repo instead of having to close issues on the main arrow repo on merge, etcetera.

We can indeed "transfer" issues between repos (for people with commit rights, the button for this is at the bottom of the right sidebar)
