### ISSUE TITLE
[R] version selector is broken

### ISSUE THREAD

**Issue by eitsupi** [apache/arrow-site#291]
The development version is displayed on the release version site and I cannot go from the release version to the development version site. ( It is possible to go to the development version site from the past version).

![image](https://user-images.githubusercontent.com/50911393/209799756-bae159f2-194b-44d3-a39a-5c412be9f88c.png)

This is due to the fact that the following lines were not updated by #273?

https://github.com/apache/arrow-site/blob/6090a411a8ad51f7ec90d3b366cee19904bc03c1/docs/r/versions.json#L2-L9

**Comment by kou** [comment]
This was fixed by https://github.com/apache/arrow/pull/14887 but it's not deployed yet. #292 will fix this.

**Comment by kou** [comment]
Deployed.

**Comment by eitsupi** [comment]
Thanks!
