### ISSUE TITLE
[QUESTION] Submitting blogposts

### ISSUE THREAD

**Issue by cakiki** [apache/arrow-site#347]
Hello! The README mentions how to go about adding a blogpost, but I was wondering what the editorial process was like. Can anyone submit a blogpost provided it be relevant to the Arrow project?

**Comment by lidavidm** [comment]
I personally don't see why not. (If only RSS wasn't dead, a 'planet' feed akin to Planet Python would be nice...)

Would you like to ask on [dev@](https://arrow.apache.org/community/) with some details of what you'd like to write about?

**Comment by cakiki** [comment]
Thank you @lidavidm ! I'll do just that. :smiley:
