### ISSUE TITLE
Update arrow-site governance page

### ISSUE THREAD

**Issue by pitrou** [apache/arrow-site#383]
The `check_committers` list indicates that our governance page is out of date:
```console
$ ../.venv/bin/python check_committers.py 
Missing PMCs in local list: ['jakevin']
Missing committers in local list: ['akurmustafa', 'avantgardner', 'gangwu', 'kevingurney', 'wayne']
Unexpected members in local list: ['avantgardnerio', 'jackwener', 'mustafasrepo', 'waynexia']
```

**Comment by pitrou** [comment]
@alamb @raulcd

**Comment by kou** [comment]
@kevingurney Do you want to update https://github.com/apache/arrow-site/blob/main/_data/committers.yml ?

**Comment by alamb** [comment]
@kevingurney  here is an example of how to do so: https://github.com/apache/arrow-site/pull/356

**Comment by alamb** [comment]
> The check_committers list indicates that our governance page is out of date:

> Missing PMCs in local list: ['jakevin']
> Missing committers in local list: ['akurmustafa', 'avantgardner', 'gangwu', 'kevingurney', 'wayne']
> Unexpected members in local list: ['avantgardnerio', 'jackwener', 'mustafasrepo', 'waynexia']

Some of these are due to members that have different github names than apache names and the github names being what is listed on the committer list. 

For example `akurmustafa` is `mustafasrepo`, 

If you have already scripted a check, perhaps we can make the script update the data automatically?

**Comment by pitrou** [comment]
> Some of these are due to members that have different github names than apache names and the github names being what is listed on the committer list.

Hmm, the current convention is to put ASF IDs in the committer list, AFAIR.

> If you have already scripted a check, perhaps we can make the script update the data automatically?

How would it do that? I think it's simpler to have people fill in the right information :-)

**Comment by kevingurney** [comment]
Thank you @kou and @alamb! I will follow up with a PR to add myself to `committers.yml`.

**Comment by kevingurney** [comment]
Follow up PR: #385

**Comment by alamb** [comment]
> How would it do that? I think it's simpler to have people fill in the right information :-)

The challenge is that you have to get humans  to do something, which is often more challenging than getting computers to do the same thing, I have found.

I was imagining the script could update the contents of `data/committers.yml` locally

Someone would still have to run it manually and make a PR but that is probably easier than keeping the contents up to date manually. 

If I get a chance I will play around with it

**Comment by alamb** [comment]
I plan to work on this issue this week

**Comment by alamb** [comment]
Here is one PR to fix incorrect aliases: https://github.com/apache/arrow-site/pull/387

Here is a second PR to add @wgtmac  https://github.com/apache/arrow-site/pull/388
