### ISSUE TITLE
[Website] Deploy step on deploy GitHub action has been failing for the last commits

### ISSUE THREAD

**Issue by raulcd** [apache/arrow-site#488]
The deploy step for the Arrow site is failing. After merging the changes are not being deployed at the moment:

See: https://github.com/apache/arrow-site/actions/workflows/deploy.yml
and a specific job: https://github.com/apache/arrow-site/actions/runs/8330658484/job/22795808856#step:9:52

```
 From https://github.com/apache/arrow-site
 * [new branch]              add-bryce  -> deploy/add-bryce
 * [new branch]              asf-site   -> deploy/asf-site
 * [new branch]              main       -> deploy/main
Switched to a new branch 'asf-site'
branch 'asf-site' set up to track 'deploy/asf-site'.
rsync: [sender] change_dir "/home/runner/work/arrow-site/arrow-site/../build/docs" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
Error: Process completed with exit code 23.
```

**Comment by raulcd** [comment]
It seems like the build step is not generating the `build/docs` folder. I am unsure if a new dependency version might have broken the build but at least jekyll is the same version.

**Comment by kou** [comment]
Ah, sorry. https://github.com/apache/arrow-site/pull/485 may be related.

**Comment by kou** [comment]
#490
